### ISSUE TITLE
работа над ошибками

### ISSUE THREAD

**Issue by Alecto** [Tina-Krua/kinozal-template-finish#1]
почему в css отступы 4 пробела?
![image](https://user-images.githubusercontent.com/8464662/121006433-92197e00-c799-11eb-80be-9772b2d5eae5.png)
в html 2?
![image](https://user-images.githubusercontent.com/8464662/121006506-a3628a80-c799-11eb-808f-5f6f031ef82f.png)
приведите проект к единому виду: или 2 или 4, но везде, включая js

**Comment by Tina-Krua** [comment]
https://tina-krua.github.io/kinozal-template-finish/
https://github.com/Tina-Krua/kinozal-template-finish

пн, 7 июн. 2021 г. в 13:09, Andrey ***@***.***>:

**Comment by Alecto** [comment]
хорошо, работа принята

пн, 7 июн. 2021 г. в 20:02, Tina Krua ***@***.***>:
